name: cropmate
description: "A plant companion."
publish_to: 'none' 
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.1.0
  # Add this line
  # app_settings: ^4.2.0
  http: ^1.1.0
  geolocator: ^10.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  super_cupertino_navigation_bar: ^2.1.2
  flutter_svg: ^2.0.17
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  # Remove the babstrap_settings_screen dependency
  shared_preferences: ^2.5.2
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  geocoding: ^2.1.0
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  haptic_feedback: ^0.5.1+1
  # tflite_flutter: ^0.11.0
  # tflite_flutter: ^0.9.0
  image: 4.5.3
  # image_pixels: ^4.0.2
  # tflite_flutter_helper: ^0.2.0
  http_parser: ^4.0.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
 # rive: ^0.11.4 # google_mlkit_image_labeling: ^0.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/plogo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/models/

